version: '3.9'
name: ${BUILD_NAME:?}
services:

  # Application image for `osmium-tool`
  # https://osmcode.org/osmium-tool/
  osmium-tool:
    build:
      context: ./osmium-tool

  #
  # DATA SOURCES
  #

  # Download GTFS zip file.
  gtfs-data:
    build:
      context: ./gtfs-data
      args:
        - GTFS_URL=${GTFS_URL:?}

  # Modify GTFS data.
  gtfs-modified:
    build:
      context: github.com/langbein-daniel/gtfs-modifications
      args:
        - BUILD_NAME=${BUILD_NAME:?}
        # If .env variable is empty, this build step is skipped. Thus no `:?`.
        - GTFS_MODIFICATION_PARAM=${GTFS_MODIFICATION_PARAM}

  # Filter GTFS data to bounding box.
  gtfs-filtered:
    build:
      context: ./gtfs-filter
      args:
        - BUILD_NAME=${BUILD_NAME:?}
        - MIN_LON=${MIN_LON:?}
        - MAX_LON=${MAX_LON:?}
        - MIN_LAT=${MIN_LAT:?}
        - MAX_LAT=${MAX_LAT:?}

  # Download OSM data.
  osm-data:
    build:
      context: ./osm-data
      args:
        - OSM_PBF_URL=${OSM_PBF_URL:?}

  # Filter OSM data to bounding box.
  osm-excerpt:
    build:
      context: ./osm-excerpt
      args:
        - BUILD_NAME=${BUILD_NAME:?}
        - MIN_LON=${MIN_LON:?}
        - MAX_LON=${MAX_LON:?}
        - MIN_LAT=${MIN_LAT:?}
        - MAX_LAT=${MAX_LAT:?}
