version: '3.9'
name: ${BUILD_NAME:?}
services:

  #
  # BACKGROUND MAP
  #

  tilemaker:
    build:
      # Build a Docker image containing the `tilemaker` command.
      # As of 2023-05-08, `tilemaker` is not yet available in `debian:stable-slim`.
      #
      # Using `FROM <git-URL> as <name>` inside the Dockerfile of the tileserver-gl service below is not (yet) possible.
      # Thus, we build the image separately.
      # https://docs.docker.com/engine/reference/commandline/build/#build-with-url
      context: github.com/systemed/tilemaker
