version: '3.9'
networks:
  proxy:
  pelias:
services:

  #
  # BACKGROUND MAP
  #

  tileserver-gl:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_TILESERVER_GL:?}
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${DOMAIN_TILESERVER_GL:?}
      LETSENCRYPT_HOST: ${DOMAIN_TILESERVER_GL:?}
    networks:
      - proxy

  #
  # ROUTING
  #

  opentripplanner:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_OPENTRIPPLANNER:?}
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${DOMAIN_OPENTRIPPLANNER:?}
      LETSENCRYPT_HOST: ${DOMAIN_OPENTRIPPLANNER:?}
    networks:
      - proxy

  #
  # GEOCODER
  #

  api:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_PELIAS_API:?}
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: 4000
      VIRTUAL_HOST: ${DOMAIN_API:?}
      LETSENCRYPT_HOST: ${DOMAIN_API:?}
    networks:
      - proxy
      - pelias
    depends_on:
      libpostal:
        condition: service_healthy
      placeholder:
        condition: service_healthy
      interpolation:
        condition: service_healthy
      pip:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  libpostal:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_PELIAS_LIBPOSTAL:?}
    restart: unless-stopped
    networks:
      - pelias

  placeholder:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_PELIAS_PLACEHOLDER:?}
    restart: unless-stopped
    networks:
      - pelias

  interpolation:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_PELIAS_INTERPOLATION:?}
    restart: unless-stopped
    networks:
      - pelias

  pip:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_PELIAS_PIP:?}
    restart: unless-stopped
    networks:
      - pelias

  elasticsearch:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_PELIAS_ELASTICSEARCH:?}
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
    security_opt:
      - seccomp=unconfined
    networks:
      - pelias

  #
  # WEB UI
  #

  digitransit-ui:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: ${IMAGE_DIGITRANSIT_UI:?}
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${DOMAIN_DIGITRANSIT_UI:?}
      LETSENCRYPT_HOST: ${DOMAIN_DIGITRANSIT_UI:?}
    networks:
      - proxy
    depends_on:
      tileserver-gl:
        condition: service_healthy
      api:
        condition: service_healthy
      opentripplanner:
        condition: service_healthy

  #
  # REVERSE PROXY & CERTIFICATES
  #

  nginx-proxy:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      # - '::0:80:80' # IPv6
      # - '::0:443:443' # IPv6
    environment:
      SSL_POLICY: Mozilla-Modern
      # ENABLE_IPV6: true
      TRUST_DOWNSTREAM_PROXY: false
    volumes:
      - ./private/conf.d:/etc/nginx/conf.d
      - ./private/vhost.d:/etc/nginx/vhost.d
      - ./private/html:/usr/share/nginx/html
      - ./private/certs:/etc/nginx/certs:ro
      - ./private/httpasswd:/etc/nginx/htpasswd:ro
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'
    networks:
      - proxy

  docker-gen:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    # nginxproxy/docker-gen:latest with added nginx.tmpl
    image: p1st/docker-gen:latest
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    volumes:
      - ./private/conf.d:/etc/nginx/conf.d
      - ./private/vhost.d:/etc/nginx/vhost.d
      - ./private/html:/usr/share/nginx/html
      - ./private/certs:/etc/nginx/certs:ro
      - ./private/httpasswd:/etc/nginx/htpasswd:ro
      #
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen'
    networks:
      - proxy

  acme-companion:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    image: nginxproxy/acme-companion
    restart: unless-stopped
    environment:
      DEFAULT_EMAIL: ${LETS_ENCRYPT_NOTIFICATION_EMAIL:?}
    volumes:
      - ./private/conf.d:/etc/nginx/conf.d
      - ./private/vhost.d:/etc/nginx/vhost.d
      - ./private/html:/usr/share/nginx/html
      - ./private/certs:/etc/nginx/certs:rw
      #
      - ./private/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    depends_on:
      - nginx-proxy
      - docker-gen

  #
  # PERIODICALLY DELETE LOG FILES
  #
  # They contain personal information such as IP addresses.
  #

  docker_cron_logging:
    image: busybox
    volumes:
      - /mnt/data/docker/containers:/docker-containers
    # Daily at 04:30: Truncate docker logfiles.
    command: >
      sh -c "
      mkdir -p /var/spool/cron/crontabs/
      && echo '30 4 * * * truncate -s 0 /docker-containers/*/*-json.log > /proc/1/fd/1 2>/proc/1/fd/2' > /var/spool/cron/crontabs/root
      && crond -f -d 8"
